package main

import (
	stan "github.com/nats-io/stan.go"
)

var many_items = "{\n\"order_uid\": \"manyitems\",\n\"track_number\": \"WBILMTESTTRACK1\",\n\"entry\": \"WBIL\",\n\"delivery\": {\n    \"name\": \"Test Testov\",\n    \"phone\": \"+9720000000\",\n    \"zip\": \"2639809\",\n    \"city\": \"Kiryat Mozkin\",\n    \"address\": \"Ploshad Mira 15\",\n    \"region\": \"Kraiot\",\n    \"email\": \"test@gmail.com\"\n},\n\"payment\": {\n    \"transaction\": \"manyitems\",\n    \"request_id\": \"\",\n    \"currency\": \"USD\",\n    \"provider\": \"wbpay\",\n    \"amount\": 1817,\n    \"payment_dt\": 1637907727,\n    \"bank\": \"alpha\",\n    \"delivery_cost\": 1500,\n    \"goods_total\": 317,\n    \"custom_fee\": 0\n},\n\"items\": [\n    {\n    \"chrt_id\": 1,\n    \"track_number\": \"WBILMTESTTRACK1\",\n    \"price\": 453,\n    \"rid\": \"ab4219087a764ae0btest\",\n    \"name\": \"whatever\",\n    \"sale\": 30,\n    \"size\": \"0\",\n    \"total_price\": 317,\n    \"nm_id\": 2389212,\n    \"brand\": \"Vivienne Sabo\",\n    \"status\": 202\n    },\n    {\n    \"chrt_id\": 666,\n    \"track_number\": \"WBILMTESTTRACK1\",\n    \"price\": 453,\n    \"rid\": \"ab4219087a764ae0btest\",\n    \"name\": \"WhiteHat\",\n    \"sale\": 30,\n    \"size\": \"0\",\n    \"total_price\": 317,\n    \"nm_id\": 2389212,\n    \"brand\": \"Vivienne Sabo\",\n    \"status\": 202\n    },\n    {\n    \"chrt_id\": 431,\n    \"track_number\": \"WBILMTESTTRACK1\",\n    \"price\": 453,\n    \"rid\": \"ab4219087a764ae0btest\",\n    \"name\": \"RedHat\",\n    \"sale\": 30,\n    \"size\": \"0\",\n    \"total_price\": 317,\n    \"nm_id\": 2389212,\n    \"brand\": \"Vivienne Sabo\",\n    \"status\": 202\n    },\n    {\n    \"chrt_id\": 123,\n    \"track_number\": \"WBILMTESTTRACK1\",\n    \"price\": 453,\n    \"rid\": \"ab4219087a764ae0btest\",\n    \"name\": \"BlackHat\",\n    \"sale\": 30,\n    \"size\": \"0\",\n    \"total_price\": 317,\n    \"nm_id\": 2389212,\n    \"brand\": \"Vivienne Sabo\",\n    \"status\": 202\n    }\n],\n\"locale\": \"en\",\n\"internal_signature\": \"\",\n\"customer_id\": \"test\",\n\"delivery_service\": \"meest\",\n\"shardkey\": \"9\",\n\"sm_id\": 99,\n\"date_created\": \"2021-11-26T06:22:19Z\",\n\"oof_shard\": \"1\"\n}"
var valid_json = "{\n  \"order_uid\": \"test\",\n  \"track_number\": \"WBILMTESTTRACKtest\",\n  \"entry\": \"WBIL\",\n  \"delivery\": {\n    \"name\": \"Test Testov\",\n    \"phone\": \"+9720000000\",\n    \"zip\": \"2639809\",\n    \"city\": \"Kiryat Mozkin\",\n    \"address\": \"Ploshad Mira 15\",\n    \"region\": \"Kraiot\",\n    \"email\": \"test@gmail.com\"\n  },\n  \"payment\": {\n    \"transaction\": \"test\",\n    \"request_id\": \"\",\n    \"currency\": \"USD\",\n    \"provider\": \"wbpay\",\n    \"amount\": 1817,\n    \"payment_dt\": 1637907727,\n    \"bank\": \"alpha\",\n    \"delivery_cost\": 1500,\n    \"goods_total\": 317,\n    \"custom_fee\": 0\n  },\n  \"items\": [\n    {\n      \"chrt_id\": 9934930,\n      \"track_number\": \"WBILMTESTTRACKtest\",\n      \"price\": 453,\n      \"rid\": \"ab4219087a764ae0btest\",\n      \"name\": \"Mascaras\",\n      \"sale\": 30,\n      \"size\": \"0\",\n      \"total_price\": 317,\n      \"nm_id\": 2389212,\n      \"brand\": \"Vivienne Sabo\",\n      \"status\": 202\n    }\n  ],\n  \"locale\": \"en\",\n  \"internal_signature\": \"\",\n  \"customer_id\": \"test\",\n  \"delivery_service\": \"meest\",\n  \"shardkey\": \"9\",\n  \"sm_id\": 99,\n  \"date_created\": \"2021-11-26T06:22:19Z\",\n  \"oof_shard\": \"1\"\n}\n"

func main() {
	sc, _ := stan.Connect("test-cluster", "simple")
	defer sc.Close()
	sc.Publish("service", []byte("{invalid}"))
	sc.Publish("service", []byte(many_items))
	sc.Publish("service", []byte(valid_json))
}
